// auth actions
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGIN_IN_PROGRESS = "USER_LOGIN_IN_PROGRESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_SIGNUP_IN_PROGRESS = "USER_SIGNUP_IN_PROGRESS";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_CLEAR_ERROR = "USER_CLEAR_ERROR";
